# Generated by Django 6.0 on 2026-01-05 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia_plus', '0043_rename_avaliar_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gerenciamento',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
